// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T3App.API;

namespace T3App.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210313112821_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("T3App.Shared.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56342401-d891-4cc4-9c1b-4fe9e11cbcb8"),
                            Name = "Bart Van Hoey"
                        },
                        new
                        {
                            Id = new Guid("7c470790-59db-4372-88c5-c352a0ff0fb7"),
                            Name = "Jakob Van Hoey"
                        },
                        new
                        {
                            Id = new Guid("6d85290b-3ead-4fdf-91a6-15a32744b504"),
                            Name = "Lukas Van Hoey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
